---
language: c
env:
  matrix:
        - APP_PATH="Digital_Input_Pure_C"
        - APP_PATH="Analog_Input_Pure_C"
        - APP_PATH="Counter_Pure_C"
        - APP_PATH="Digital_Output_Pure_C"
        - APP_PATH="Analog_Output_Pure_C"
        - APP_PATH="PWM_Pure_C"
        - APP_PATH="Timer_Pure_C"
before_install:
  - sudo apt-get update -qq
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
  - ln -s $PWD /usr/local/share/arduino/libraries/Adafruit_FONA
  - arduino --install-library "Adafruit SleepyDog Library,Adafruit MQTT Library"
script:
  - avr-gcc --version
  - cd $APP_PATH
  - make
  - arduino --verify --board arduino:avr:uno Analog_Input_with_Arduino.ino
  - arduino --verify --board arduino:avr:uno Timer_2_with_Arduino.ino
  - arduino --verify --board arduino:avr:uno PWM_using_Arduino.ino
