---
language: c
env:
  matrix:
        - APP_PATH="Digital_Input_Pure_C"
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
script:
  - avr-gcc --version
  - cd $APP_PATH
  - make
